### ISSUE TITLE
IntegrityError > CHECK constraint failed: donations

### ISSUE THREAD

**Issue by justinmayer** [ddevault/fosspay#12]
Many thanks for creating this project, Drew. I think the idea and implementation are both fantastic. Looking forward to using it for [Pelican](https://github.com/getpelican/pelican). 🥇 

Using SQLite via `connection-string=sqlite:////db/fosspay.db`, I started fosspay for the first time and encountered the following error in Gunicorn's logs:

<details><summary>[tap to see log output > sqlite3.OperationalError: table users already exists]</summary><blockquote>

~~~
[2019-05-25 10:22:12 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-05-25 10:22:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2019-05-25 10:22:12 +0000] [1] [INFO] Using worker: sync
[2019-05-25 10:22:12 +0000] [7] [INFO] Booting worker with pid: 7
[2019-05-25 10:22:12 +0000] [8] [INFO] Booting worker with pid: 8
[2019-05-25 10:22:18 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table users already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/app.py", line 2, in <module>
    from fosspay.app import app
  File "/app/fosspay/app.py", line 21, in <module>
    init_db()
  File "/app/fosspay/database.py", line 14, in init_db
    Base.metadata.create_all(bind=engine)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table users already exists
[SQL: 
CREATE TABLE users (
	id INTEGER NOT NULL, 
	email VARCHAR(256) NOT NULL, 
	admin BOOLEAN, 
	password VARCHAR, 
	created DATETIME, 
	password_reset VARCHAR(128), 
	password_reset_expires DATETIME, 
	stripe_customer VARCHAR(256), 
	PRIMARY KEY (id), 
	CHECK (admin IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2019-05-25 10:22:18 +0000] [8] [INFO] Worker exiting (pid: 8)
[2019-05-25 10:22:18 +0000] [7] [INFO] Worker exiting (pid: 7)
[2019-05-25 10:22:19 +0000] [1] [INFO] Shutting down: Master
[2019-05-25 10:22:19 +0000] [1] [INFO] Reason: Worker failed to boot.
~~~
</blockquote></details>

I don't understand why the above error occurred, but restarting Gunicorn appeared to resolve that issue, as I was able to subsequently able to load the web application and create an initial admin user.

However, when trying to make a donation (via a new session in a different browser), I encountered the following error:

<details><summary>[tap to see log output > IntegrityError > CHECK constraint failed: donations]</summary><blockquote>

~~~
[2019-06-02 05:41:52 +0000] [1] [DEBUG] Current configuration:
  config: None
  bind: ['0.0.0.0:8002']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: gunicorn-fosspay-pelican
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f6fc5f91048>
  on_reload: <function OnReload.on_reload at 0x7f6fc5f91158>
  when_ready: <function WhenReady.when_ready at 0x7f6fc5f91268>
  pre_fork: <function Prefork.pre_fork at 0x7f6fc5f91378>
  post_fork: <function Postfork.post_fork at 0x7f6fc5f91488>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f6fc5f91598>
  worker_int: <function WorkerInt.worker_int at 0x7f6fc5f916a8>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f6fc5f917b8>
  pre_exec: <function PreExec.pre_exec at 0x7f6fc5f918c8>
  pre_request: <function PreRequest.pre_request at 0x7f6fc5f919d8>
  post_request: <function PostRequest.post_request at 0x7f6fc5f91a60>
  child_exit: <function ChildExit.child_exit at 0x7f6fc5f91b70>
  worker_exit: <function WorkerExit.worker_exit at 0x7f6fc5f91c80>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f6fc5f91d90>
  on_exit: <function OnExit.on_exit at 0x7f6fc5f91ea0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-06-02 05:41:52 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-06-02 05:41:52 +0000] [1] [DEBUG] Arbiter booted
[2019-06-02 05:41:52 +0000] [1] [INFO] Listening at: http://0.0.0.0:8002 (1)
[2019-06-02 05:41:52 +0000] [1] [INFO] Using worker: sync
[2019-06-02 05:41:52 +0000] [7] [INFO] Booting worker with pid: 7
[2019-06-02 05:41:52 +0000] [8] [INFO] Booting worker with pid: 8
[2019-06-02 05:41:52 +0000] [1] [DEBUG] 2 workers
[2019-06-02 05:42:06 +0000] [7] [DEBUG] GET /
[2019-06-02 05:42:07 +0000] [8] [DEBUG] GET /static/index.js
[2019-06-02 05:42:07 +0000] [7] [DEBUG] GET /static/icon.png
[2019-06-02 05:43:40 +0000] [7] [DEBUG] POST /donate
[2019-06-02 05:43:42 +0000] [7] [ERROR] Error handling request /donate
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: CHECK constraint failed: donations

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fosspay/common.py", line 66, in wrapper
    result = f(*args, **kwargs)
  File "/app/fosspay/blueprints/html.py", line 217, in donate
    db.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) CHECK constraint failed: donations
[SQL: INSERT INTO donations (user_id, project_id, type, amount, created, updated, comment, active, payments) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (2, None, 'one_time', 3000, '2019-06-02 05:43:41.899985', '2019-06-02 05:43:41.899994', 'Thank you for Pelican!', 1, 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
~~~
</blockquote></details>

There is only one user in the database: the admin user I created when loading the web application for the first time. It looks like the SQL invocation that caused the error is referencing user ID 2, which does not exist. I don't know if that has anything to do with this error or not.

Might you have any suggestions as to how I could troubleshoot and resolve this problem?

**Comment by ddevault** [comment]
Hiya! I don't test this on sqlite. Can you try setting up a postgresql server instead?

**Comment by ddevault** [comment]
Aside: I don't know what this "fathom" command is.

**Comment by justinmayer** [comment]
Hey Drew. Many thanks for responding so quickly. Please ignore the `fathom` command I mentioned previously. I clearly did not have enough coffee when I wrote that part of the description, which I have since fixed. Mea culpa.

I can try using a PG server instead. I had hoped to use SQLite for this particular application, in part because I'm using fosspay in a Dockerized environment and find it vastly simpler to deal with the file-based SQLite database as opposed to having to create a new PG container and volume for each fosspay instance, of which I will have at least two.

**Comment by ddevault** [comment]
You're totally welcome to try and get it working with sqlite, I don't see any reason why it couldn't... but you're on your own for that, patches welcome.

**Comment by justinmayer** [comment]
Given my shallow experience with Flask+SQLalchemy, I don't know that I would get very far trying to get fosspay to work well with SQLite. So I'll take your suggestion and try setting it up with PostgreSQL instead. Will update this issue shortly with the results of that endeavor.

**Comment by justinmayer** [comment]
Switching from SQLite to PostgreSQL did indeed resolve the problems described in this issue. While I was tempted to submit a PR to add a note to the README mentioning that SQLite is not supported, after re-reading it I realized that the requirements very explicitly include PostgreSQL, so this is mostly a failure to read properly on my part. 😅  Thanks again for the assistance!
