### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by Golumpa** [ddevault/fosspay#7]
Hey, trying to setup FossPay and seem to be getting an error on running the app.py.

I have set up the config however seem to still get the error.
Running Python 3.5.2

```python3 app.py

 * Serving Flask app "fosspay.app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://IP.ADDRESS:5000/ (Press CTRL+C to quit)
MY.IP.ADDRESS - - [12/Jan/2019 23:42:16] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/USER/fosspay/fosspay/blueprints/html.py", line 25, in index
    load_config()
  File "/var/www/USER/fosspay/fosspay/config.py", line 30, in load_config
    signal.signal(signal.SIGHUP, lambda *args: load_config())
  File "/usr/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread```

**Comment by ddevault** [comment]
Hmm, I can't reproduce this. I'm using Python 3.7.2.

**Comment by Golumpa** [comment]
How would I go at disabling this, I have added "use_reloader=False" to the app.run as I have read that is it but still not working.

**Comment by ddevault** [comment]
Look at the stack trace - the code is in config.py.

**Comment by Golumpa** [comment]
Ah silly me, thanks for the help At least i can get this working now.

**Comment by MaxDesiatov** [comment]
This is also reproducible for me with the latest code from `master` with Python 3.7.3.

**Comment by r14c** [comment]
i am able to reproduce this if i use `gunicorn -k gthread`, but i'm not sure if that worker class is meant to be supported by `fosspay`.

**Comment by r14c** [comment]
i modified `fosspay/config.py` so it warns about this condition, but doesn't fail.

```
def load_config():
    # ...
    try:
        signal.signal(signal.SIGHUP, lambda *args: load_config())
    except ValueError as e:
        logger.warn(e)
```

its a trivial change, but i can open a PR.

**Comment by shleeable** [comment]
I had the same problem. Patch above fixed it.
